include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    non_constant_identifier_names: ignore
    constant_identifier_names: ignore
