include: package:very_good_analysis/analysis_options.3.0.1.yaml
linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude: [
    build/**,
    lib/**.freezed.dart,
    lib/**.g.dart,
    lib/**.config.dart,
    lib/l10n/gen/
  ]