name: expense_tracker
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.3.9'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  badges: ^2.0.3
  cloud_firestore: ^4.1.0 
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  drift: ^2.1.0
  drift_db_viewer: ^2.0.0
  file_picker: ^5.2.2
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_dynamic_links: ^5.0.6
  fl_chart: ^0.55.0
  flex_color_picker: ^3.0.0
  flutter:
    sdk: flutter  
  flutter_bloc: ^8.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_emoji: ^2.4.0
  flutter_iconpicker: ^3.2.2
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.3+1
  flutter_svg: ^1.1.4
  font_awesome_flutter: ^10.1.0
  formz: ^0.4.1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  go_router: ^5.2.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  injectable: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  logger: ^1.1.0
  mockingjay: ^0.3.0
  path: ^1.8.2
  path_provider: ^2.0.11
  pinput: ^2.2.12
  provider: ^6.0.3
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8
  sqlite3_flutter_libs: ^0.5.12
  table_calendar: ^3.0.2
  # transaction_repository:
  #   path: packages/transaction_repository
  timezone: ^0.9.1
  uuid: ^3.0.5
  # wallet_repository:
  #   path: packages/wallet_repository

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  drift_dev: ^2.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^2.0.0
  json_serializable: ^6.0.0 
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/banks/
    - assets/icons/categories/

flutter_gen:
  line_length: 80 

  integrations:
    flutter_svg: true
