name: Example workflow for Codecov
on: push
jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: "3.3.0"
      min_coverage: 0
      coverage_excludes: "*.g.dart *.freezed.dart firebase_options_dev.dart firebase_options.dart"
  
  upload-codecov:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: ${{github.event.pull_request_target.head.ref}}
        repository: ${{github.event.pull_request_target.head.repo.full_name}}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
        token: ${{secrets.CODECOV_TOKEN}}