# .github/workflows/my_flutter_package.yaml
name: my_flutter_package
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
