name: Example workflow for Codecov
on: [push]
jobs:
  uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
  run:
    steps:
    # - uses: actions/checkout@master
    # - name: Setup Python
    #   uses: actions/setup-python@master
    #   with:
    #     python-version: 3.7
    # - name: Generate coverage report
    #   run: |
    #     pip install pytest
    #     pip install pytest-cov
    #     pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info
        # token: ${{ secrets.CODECOV_TOKEN }}
        # directory: ./coverage/reports/
        # env_vars: OS,PYTHON
        # fail_ci_if_error: true
        # files: ./coverage1.xml,./coverage2.xml
        # flags: unittests
        # name: codecov-umbrella
        # path_to_write_report: ./coverage/codecov_report.txt
        # verbose: true